version: 2.1
  node: circleci/node@1.1.6
jobs:
  build:
    docker:
      - image: circleci/node:12


    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Run tests
          command: |
            npm test
workflows:
  build_and_test:
    jobs:
      - build