version: 2.1
jobs:
  sandbox:
    machine:
      image: ubuntu-1604:202004-01
      docker_layer_caching: true
    steps:
     - checkout
     - run:
        name: Build Docker image
        command: docker build -t takumab/node-hello-world-app .
     - run:
         name: Push image to Docker Hub
         command: |
           echo "$DOCKERHUB_PASS" | docker login -u "$DOCKER_NAME" --password-stdin
           docker push codurance/hello-walking-skeleton-project:${CIRCLE_SHA1}

workflows:
  build_and_test:
    jobs:
      - sandbox
