version: 2.1
jobs:
  sandbox:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: ./docker_build.sh
      - run: ./docker_run_test.sh



workflows:
  sandbox:
    jobs:
      - sandbox