version: 2.1
jobs:
  sandbox:
    machine:
      image: ubuntu-1604:202004-01
      docker_layer_caching: true
    steps:
     - checkout
     - aws-cli/setup
     - run:
         name: Build and push docker image to AWS ECR
         command: |
           aws ecr get-login-password | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
           docker build -t hello-walking-skeleton-project:${CIRCLE_SHA1} .
           docker tag hello-walking-skeleton-project:${CIRCLE_SHA1} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:${CIRCLE_SHA1}
           docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:${CIRCLE_SHA1}
  sandbox_test:
     machine:
       image: ubuntu-1604:202004-01
       docker_layer_caching: true
     steps:
       - aws-cli/setup
       - run:
          name: Pull image from ECR and run tests
          command: |
            aws ecr get-login-password | docker login  \
            --username AWS \
            --password-stdin \
            ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
            docker pull ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:${CIRCLE_SHA1}
            docker run ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:${CIRCLE_SHA1} npm test

orbs:
  aws-cli: circleci/aws-cli@1.1.0
workflows:
  build_and_test:
    jobs:
      - sandbox
      - sandbox_test:
          requires:
            - sandbox
