version: 2.1
jobs:
  build:
    docker:
     - image: circleci/node:12
    steps:
     - checkout
     - setup_remote_docker
     - run:
        name: Build Docker image
        command: docker build -t takumab/node-hello-world-app .
     - run:
        name: Run tests inside Docker container
        command: docker run takumab/node-hello-world-app npm test

workflows:
  build_and_test:
    jobs:
      - build