version: 2.1
jobs:
  sandbox:
    steps:
      - checkout
      - run: docker build -t takumab/node-hello-world-app .
      - run: docker run takumab/node-hello-world-app npm test



workflows:
  sandbox:
    jobs:
      - sandbox