version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01
    steps:
     - checkout
     - run:
        name: Build Docker image
        command: docker build -t takumab/node-hello-world-app .
     - run:
        name: Run tests inside Docker container
        command: docker run takumab/node-hello-world-app npm test

workflows:
  build_and_test:
    jobs:
      - build
